# Generated by Django 3.2.12 on 2023-06-01 13:48

import MyModel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.IntegerField(choices=[(0, 'Text Only'), (1, 'Media')], default=0)),
                ('media_url', models.FileField(blank=True, null=True, upload_to=MyModel.models.comment_media_path)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=MyModel.models.user_picture_path)),
                ('username', models.CharField(max_length=50)),
                ('passward', models.CharField(max_length=100)),
                ('phonenum', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.comment')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyModel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content_type', models.IntegerField(choices=[(0, 'Text Only'), (1, 'Media')], default=0)),
                ('text', models.CharField(max_length=1200)),
                ('media_url', models.FileField(blank=True, null=True, upload_to=MyModel.models.post_media_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyModel.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyModel.user'),
        ),
    ]
