# Generated by Django 3.2.12 on 2023-06-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
